on: [push]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: envkey=${{ secrets.envkey }}
          script: |
            set -e  # Exit if a command fails
            
            echo 'Starting SSH commands execution on the remote server...'
            
            # Navigate to the project directory
            cd domains/filmsocket.com || exit 1
            
            # Check if the repository is already cloned, else clone it
            if [ -d "myfiles/.git" ]; then
              echo "Repository found, pulling latest changes..."
              cd myfiles
              git fetch origin main
              git reset --hard origin/main
            else
              echo "Cloning the repository..."
              git clone https://github.com/dhawandj/dj.git myfiles
              cd myfiles

              # Install PHP dependencies
              echo "Installing PHP dependencies..."
              composer install --no-interaction --prefer-dist --optimize-autoloader
              
              # Decrypt the .env file if necessary
              # php artisan env:decrypt --key=${{ secrets.envkey }}
              php artisan env:decrypt --key="${envkey}"

              # Run Laravel setup (optional commands)
              echo "Running Laravel setup..."
              # Uncomment the lines below if needed:
              php artisan migrate:fresh --force
              php artisan cache:clear
              php artisan config:cache
              php artisan route:cache
              
            fi
            
            # Display directory contents for confirmation
            echo "Current files in $(pwd):"
            ls -la

            # Install PHP dependencies
            echo "Installing PHP dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader
            
            # Run Laravel setup (optional commands)
            echo "Running Laravel setup..."
            # Uncomment the lines below if needed:
            # php artisan migrate --force
            # php artisan cache:clear
            # php artisan config:cache
            # php artisan route:cache
            
            echo "Deployment completed successfully!"
