name: Test Deploy to Hostinger with SFTP

on:
  push:
    branches:
      - main  # Only trigger on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SFTP Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"  # Adjust as needed
          SOURCE: "./test.txt"  # Path to the test file in your repo
          REMOTE_HOST: ${{ secrets.FTP_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          TARGET: "/public_html/"  # Destination path on your server
